### ISSUE TITLE
Amazon SES logging

### ISSUE THREAD

**Issue by szepeviktor** [oprudkyi/laravel-mail-logger#1]
@oprudkyi Thank you for the logger. It work fine for SMTP transport.

We use Amazon SES (HTTP API) Transport and there is nothing logged.

Please advise.

**Comment by oprudkyi** [comment]
Hi ,
Sorry for delay with answer. 
It seems like SES integration uses different stack (i.e. amazon/guzzlehttp instead of swiftmailer) so it won't be possible to log it. 
so, unfortunately, you still will need to use receipts from http://docs.aws.amazon.com/ses/latest/DeveloperGuide/delivery-problems.html

**Comment by szepeviktor** [comment]
Thank you.
So your project is a swiftmailer logger, not a general Laravel mail transport logger.

**Comment by szepeviktor** [comment]
My aim was to log the return value of Mail::send() and the To: field.

**Comment by oprudkyi** [comment]
as temporal solution you can embed your logging functionality into 
vendor/laravel/framework/src/Illuminate/Mail/Transport/SesTransport.php
